[package]
name = "assign5"
version = "0.1.0"
authors = ["Will Crichton <wcrichto@cs.stanford.edu>"]

[dependencies]
clap = "2.32"
nom = "4.0"

[lib]
name = "memory"
path = "src/memory.rs"

[[bin]]
name = "assign5"
path = "src/main.rs"